/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * The verbatim source of each strategy's decide() (and the helper / indicator
 * functions it calls), surfaced to the UI as the buy/sell signal formula so the
 * displayed math can never drift from the code that runs.
 *
 * Regenerate after editing any decide():
 *   cd backend && node scripts/generate-signal-source.mjs
 *
 * signal-source.spec.ts fails CI if this file is stale.
 */
import type { SignalSource } from '@repo/shared';

export const SIGNAL_SOURCE: Record<string, SignalSource> = {
  "nasdaq-3x-20dma": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const price = ctx.level(ASSET.NASDAQ);\n    const ma = ctx.sma(ASSET.NASDAQ, 20);\n    if (price === undefined || ma === undefined) return {};\n    return price > ma ? { [ASSET.NASDAQ3X]: 1 } : {};\n  }",
    refs: [
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
    ],
  },
  "s1-tsmom-managed-futures": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const sleeves = [ASSET.NASDAQ, ASSET.LTT, ASSET.GOLD];\n    // Each sleeve held only if its own 12-month absolute momentum is positive AND in uptrend.\n    const on = sleeves.filter(\n      (a) => (ctx.ret(a, 252) ?? -1) > 0 && trendUp(ctx, a, 200) && ctx.has(a),\n    );\n    if (!on.length) return { [ASSET.CASH]: 1 };\n    let w = equalWeight(on, 1);\n    // Express the equity sleeve (Nasdaq) with vol-targeted leverage to lift compounding.\n    const eqBudget = w[ASSET.NASDAQ];\n    if (eqBudget) {\n      delete w[ASSET.NASDAQ];\n      w = addW(w, leveragedEquity(ctx, ASSET.NASDAQ, ASSET.NASDAQ2X, undefined, eqBudget, 0.3, 2));\n    }\n    return capHoldings(w, 10);\n  }",
    refs: [
      { name: "ret", source: "export function ret(lv: Levels, i: number, period: number): number | undefined {\n  const now = lv[i];\n  const then = lv[i - period];\n  if (now === undefined || then === undefined) return undefined;\n  return now / then - 1;\n}" },
      { name: "trendUp", source: "export function trendUp(ctx: StrategyContext, asset: AssetKey, period = 200): boolean {\n  const p = ctx.level(asset);\n  const ma = ctx.sma(asset, period);\n  return p !== undefined && ma !== undefined && p > ma;\n}" },
      { name: "equalWeight", source: "export function equalWeight(assets: AssetKey[], budget = 1): Weights {\n  const w: Weights = {};\n  if (assets.length === 0) return w;\n  for (const a of assets) w[a] = budget / assets.length;\n  return w;\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "addW", source: "export function addW(...weights: Weights[]): Weights {\n  const out: Weights = {};\n  for (const w of weights) {\n    for (const a of Object.keys(w) as AssetKey[]) out[a] = (out[a] ?? 0) + (w[a] ?? 0);\n  }\n  return out;\n}" },
      { name: "leveragedEquity", source: "export function leveragedEquity(\n  ctx: StrategyContext,\n  oneX: AssetKey,\n  twoX: AssetKey | undefined,\n  threeX: AssetKey | undefined,\n  budget: number,\n  target = 0.3,\n  cap = 2,\n): Weights {\n  const exposure = volTargetExposure(ctx, oneX, target, cap);\n  return scaleWeights(equityExposureWeights(exposure, oneX, twoX, threeX), budget);\n}" },
      { name: "capHoldings", source: "export function capHoldings(w: Weights, maxN: number): Weights {\n  const entries = (Object.entries(w) as [AssetKey, number][]).filter(([, x]) => (x ?? 0) > 0);\n  if (entries.length <= maxN) return w;\n  entries.sort((a, b) => b[1] - a[1]);\n  const kept = entries.slice(0, maxN);\n  const grossAll = entries.reduce((s, [, x]) => s + x, 0);\n  const grossKept = kept.reduce((s, [, x]) => s + x, 0);\n  const scale = grossKept > 0 ? grossAll / grossKept : 1;\n  const out: Weights = {};\n  for (const [a, x] of kept) out[a] = Number((x * scale).toFixed(4));\n  return out;\n}" },
    ],
  },
  "s2-dual-momentum-gem": {
    decide: "decide(ctx: StrategyContext): Weights {\n    // Absolute-momentum gate: is US equity beating cash over 12 months?\n    const eqMom = ctx.ret(ASSET.USLC, 252);\n    const cashMom = ctx.ret(ASSET.CASH, 252);\n    if (eqMom === undefined || cashMom === undefined || eqMom <= cashMom) {\n      return { [bestDefensive(ctx)]: 1 };\n    }\n    // Relative momentum: stronger of US growth (Nasdaq) vs developed-international.\n    const us = ctx.score13612W(ASSET.NASDAQ) ?? ctx.score13612W(ASSET.USLC) ?? -1;\n    const intl = ctx.has(ASSET.INTL) ? (ctx.score13612W(ASSET.INTL) ?? -1) : -Infinity;\n    if (us >= intl) return leveragedEquity(ctx, ASSET.NASDAQ, ASSET.NASDAQ2X, undefined, 1, 0.3, 2);\n    return { [ASSET.INTL]: 1 };\n  }",
    refs: [
      { name: "ret", source: "export function ret(lv: Levels, i: number, period: number): number | undefined {\n  const now = lv[i];\n  const then = lv[i - period];\n  if (now === undefined || then === undefined) return undefined;\n  return now / then - 1;\n}" },
      { name: "bestDefensive", source: "export function bestDefensive(ctx: StrategyContext): AssetKey {\n  return bestBy([ASSET.ITT, ASSET.LTT, ASSET.GOLD, ASSET.CASH], (a) => ctx.ret(a, 126), ASSET.CASH);\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
      { name: "leveragedEquity", source: "export function leveragedEquity(\n  ctx: StrategyContext,\n  oneX: AssetKey,\n  twoX: AssetKey | undefined,\n  threeX: AssetKey | undefined,\n  budget: number,\n  target = 0.3,\n  cap = 2,\n): Weights {\n  const exposure = volTargetExposure(ctx, oneX, target, cap);\n  return scaleWeights(equityExposureWeights(exposure, oneX, twoX, threeX), budget);\n}" },
    ],
  },
  "s3-vol-managed-equity": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const v = ctx.vol(ASSET.NASDAQ, DAYS.MONTH);\n    if (v === undefined) return { [ASSET.CASH]: 1 };\n    // Moreira-Muir inverse-variance scaling: exposure = targetVar / realizedVar.\n    const E = clamp((0.2 * 0.2) / (v * v), 0, 2);\n    const w = equityExposureWeights(E, ASSET.NASDAQ, ASSET.NASDAQ2X);\n    const invested = Object.values(w).reduce<number>((s, x) => s + (x ?? 0), 0);\n    // Park the un-levered remainder in the best-trending defensive sleeve.\n    if (invested < 0.999) w[bestDefensive(ctx)] = Number((1 - invested).toFixed(4));\n    return w;\n  }",
    refs: [
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "DAYS", source: "export const DAYS = {\n  WEEK: 5,\n  MONTH: 21,\n  QUARTER: 63,\n  HALF_YEAR: 126,\n  YEAR: 252,\n};" },
      { name: "clamp", source: "export function clamp(x: number, lo: number, hi: number): number {\n  return Math.max(lo, Math.min(hi, x));\n}" },
      { name: "equityExposureWeights", source: "export function equityExposureWeights(\n  E: number,\n  oneX: AssetKey,\n  twoX?: AssetKey,\n  threeX?: AssetKey,\n): Weights {\n  const maxE = threeX ? 3 : twoX ? 2 : 1;\n  const e = clamp(E, 0, maxE);\n  if (e <= 1) return e > 0 ? { [oneX]: Number(e.toFixed(4)) } : {};\n  if (e <= 2 && twoX) {\n    const x = e - 1;\n    return { [twoX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  if (threeX) {\n    const x = (e - 1) / 2;\n    return { [threeX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  return { [oneX]: 1 };\n}" },
      { name: "bestDefensive", source: "export function bestDefensive(ctx: StrategyContext): AssetKey {\n  return bestBy([ASSET.ITT, ASSET.LTT, ASSET.GOLD, ASSET.CASH], (a) => ctx.ret(a, 126), ASSET.CASH);\n}" },
    ],
  },
  "s4-yield-curve-macro": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const tnx = ctx.yieldVal('TNX');\n    const irx = ctx.yieldVal('IRX');\n    const curve = tnx !== undefined && irx !== undefined ? tnx - irx : undefined;\n    // Inverted curve (10y < 3m) → recession warning → risk-off.\n    if (curve !== undefined && curve < 0) return { [bestDefensive(ctx)]: 1 };\n    // Broken trend → risk-off.\n    if (!trendUp(ctx, ASSET.USLC, 200)) return { [bestDefensive(ctx)]: 1 };\n    // Healthy curve + uptrend → vol-targeted leveraged S&P.\n    return leveragedEquity(ctx, ASSET.USLC, ASSET.USLC2X, undefined, 1, 0.3, 2);\n  }",
    refs: [
      { name: "bestDefensive", source: "export function bestDefensive(ctx: StrategyContext): AssetKey {\n  return bestBy([ASSET.ITT, ASSET.LTT, ASSET.GOLD, ASSET.CASH], (a) => ctx.ret(a, 126), ASSET.CASH);\n}" },
      { name: "trendUp", source: "export function trendUp(ctx: StrategyContext, asset: AssetKey, period = 200): boolean {\n  const p = ctx.level(asset);\n  const ma = ctx.sma(asset, period);\n  return p !== undefined && ma !== undefined && p > ma;\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "leveragedEquity", source: "export function leveragedEquity(\n  ctx: StrategyContext,\n  oneX: AssetKey,\n  twoX: AssetKey | undefined,\n  threeX: AssetKey | undefined,\n  budget: number,\n  target = 0.3,\n  cap = 2,\n): Weights {\n  const exposure = volTargetExposure(ctx, oneX, target, cap);\n  return scaleWeights(equityExposureWeights(exposure, oneX, twoX, threeX), budget);\n}" },
    ],
  },
  "s5-sector-momentum": {
    decide: "decide(ctx: StrategyContext): Weights {\n    if (!trendUp(ctx, ASSET.USLC, 200)) return { [bestDefensive(ctx)]: 1 };\n    const avail = SECTOR_ASSETS.filter((a) => ctx.has(a));\n    // Sectors not available pre-1998 → leveraged broad index (correct ETF-based leverage).\n    if (avail.length < 3)\n      return leveragedEquity(ctx, ASSET.NASDAQ, ASSET.NASDAQ2X, undefined, 1, 0.3, 2);\n    const top = rankBy(avail, (a) => ctx.score13612W(a))\n      .slice(0, 3)\n      .map((x) => x.asset)\n      .filter((a) => (ctx.score13612W(a) ?? -1) > 0);\n    if (!top.length) return { [bestDefensive(ctx)]: 1 };\n    // 70% into the strongest sectors + a 30% vol-targeted leveraged S&P core (gross = 1).\n    const sectors = equalWeight(top, 0.7);\n    const core = leveragedEquity(ctx, ASSET.USLC, ASSET.USLC2X, undefined, 0.3, 0.3, 2);\n    return capHoldings(addW(sectors, core), 10);\n  }",
    refs: [
      { name: "trendUp", source: "export function trendUp(ctx: StrategyContext, asset: AssetKey, period = 200): boolean {\n  const p = ctx.level(asset);\n  const ma = ctx.sma(asset, period);\n  return p !== undefined && ma !== undefined && p > ma;\n}" },
      { name: "bestDefensive", source: "export function bestDefensive(ctx: StrategyContext): AssetKey {\n  return bestBy([ASSET.ITT, ASSET.LTT, ASSET.GOLD, ASSET.CASH], (a) => ctx.ret(a, 126), ASSET.CASH);\n}" },
      { name: "leveragedEquity", source: "export function leveragedEquity(\n  ctx: StrategyContext,\n  oneX: AssetKey,\n  twoX: AssetKey | undefined,\n  threeX: AssetKey | undefined,\n  budget: number,\n  target = 0.3,\n  cap = 2,\n): Weights {\n  const exposure = volTargetExposure(ctx, oneX, target, cap);\n  return scaleWeights(equityExposureWeights(exposure, oneX, twoX, threeX), budget);\n}" },
      { name: "rankBy", source: "export function rankBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n): { asset: AssetKey; score: number }" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "equalWeight", source: "export function equalWeight(assets: AssetKey[], budget = 1): Weights {\n  const w: Weights = {};\n  if (assets.length === 0) return w;\n  for (const a of assets) w[a] = budget / assets.length;\n  return w;\n}" },
      { name: "capHoldings", source: "export function capHoldings(w: Weights, maxN: number): Weights {\n  const entries = (Object.entries(w) as [AssetKey, number][]).filter(([, x]) => (x ?? 0) > 0);\n  if (entries.length <= maxN) return w;\n  entries.sort((a, b) => b[1] - a[1]);\n  const kept = entries.slice(0, maxN);\n  const grossAll = entries.reduce((s, [, x]) => s + x, 0);\n  const grossKept = kept.reduce((s, [, x]) => s + x, 0);\n  const scale = grossKept > 0 ? grossAll / grossKept : 1;\n  const out: Weights = {};\n  for (const [a, x] of kept) out[a] = Number((x * scale).toFixed(4));\n  return out;\n}" },
      { name: "addW", source: "export function addW(...weights: Weights[]): Weights {\n  const out: Weights = {};\n  for (const w of weights) {\n    for (const a of Object.keys(w) as AssetKey[]) out[a] = (out[a] ?? 0) + (w[a] ?? 0);\n  }\n  return out;\n}" },
    ],
  },
  "s6-risk-parity": {
    decide: "decide(ctx: StrategyContext): Weights {\n    // Risk-parity sleeves: equity, long bonds, gold — kept only if trending up.\n    const sleeves = [ASSET.NASDAQ, ASSET.LTT, ASSET.GOLD].filter(\n      (a) => ctx.has(a) && trendUp(ctx, a, 200),\n    );\n    if (!sleeves.length) return { [ASSET.CASH]: 1 };\n    let w = invVol(ctx, sleeves, DAYS.HALF_YEAR, 1);\n    // Lever the equity sleeve by vol-target (the HFEA idea: lever the risk-parity book).\n    const eqBudget = w[ASSET.NASDAQ];\n    if (eqBudget) {\n      delete w[ASSET.NASDAQ];\n      w = addW(w, leveragedEquity(ctx, ASSET.NASDAQ, ASSET.NASDAQ2X, undefined, eqBudget, 0.3, 2));\n    }\n    return capHoldings(w, 10);\n  }",
    refs: [
      { name: "trendUp", source: "export function trendUp(ctx: StrategyContext, asset: AssetKey, period = 200): boolean {\n  const p = ctx.level(asset);\n  const ma = ctx.sma(asset, period);\n  return p !== undefined && ma !== undefined && p > ma;\n}" },
      { name: "invVol", source: "export function invVol(\n  ctx: StrategyContext,\n  assets: AssetKey[],\n  volDays: number,\n  budget = 1,\n): Weights {\n  const raw = assets.map((asset) => {\n    const v = ctx.vol(asset, volDays);\n    return { asset, inv: v && v > 0 ? 1 / v : 0 };\n  });\n  const total = raw.reduce((s, r) => s + r.inv, 0);\n  const w: Weights = {};\n  if (total === 0) {\n    for (const a of assets) w[a] = budget / Math.max(1, assets.length);\n    return w;\n  }\n  for (const r of raw) if (r.inv > 0) w[r.asset] = Number(((r.inv / total) * budget).toFixed(4));\n  return w;\n}" },
      { name: "DAYS", source: "export const DAYS = {\n  WEEK: 5,\n  MONTH: 21,\n  QUARTER: 63,\n  HALF_YEAR: 126,\n  YEAR: 252,\n};" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "addW", source: "export function addW(...weights: Weights[]): Weights {\n  const out: Weights = {};\n  for (const w of weights) {\n    for (const a of Object.keys(w) as AssetKey[]) out[a] = (out[a] ?? 0) + (w[a] ?? 0);\n  }\n  return out;\n}" },
      { name: "leveragedEquity", source: "export function leveragedEquity(\n  ctx: StrategyContext,\n  oneX: AssetKey,\n  twoX: AssetKey | undefined,\n  threeX: AssetKey | undefined,\n  budget: number,\n  target = 0.3,\n  cap = 2,\n): Weights {\n  const exposure = volTargetExposure(ctx, oneX, target, cap);\n  return scaleWeights(equityExposureWeights(exposure, oneX, twoX, threeX), budget);\n}" },
      { name: "capHoldings", source: "export function capHoldings(w: Weights, maxN: number): Weights {\n  const entries = (Object.entries(w) as [AssetKey, number][]).filter(([, x]) => (x ?? 0) > 0);\n  if (entries.length <= maxN) return w;\n  entries.sort((a, b) => b[1] - a[1]);\n  const kept = entries.slice(0, maxN);\n  const grossAll = entries.reduce((s, [, x]) => s + x, 0);\n  const grossKept = kept.reduce((s, [, x]) => s + x, 0);\n  const scale = grossKept > 0 ? grossAll / grossKept : 1;\n  const out: Weights = {};\n  for (const [a, x] of kept) out[a] = Number((x * scale).toFixed(4));\n  return out;\n}" },
    ],
  },
  "s7-rsi2-mean-reversion": {
    decide: "decide(ctx: StrategyContext): Weights {\n    // Only buy dips in an uptrend; risk-off below the 200-day MA.\n    if (!trendUp(ctx, ASSET.NASDAQ, 200)) return { [bestDefensive(ctx)]: 1 };\n    const r = ctx.rsi(ASSET.NASDAQ, 2);\n    // Oversold → vol-targeted leveraged long (cap 1.5x).\n    if (r !== undefined && r <= 10) {\n      return leveragedEquity(ctx, ASSET.NASDAQ, ASSET.NASDAQ2X, undefined, 1, 0.3, 1.5);\n    }\n    // Overbought → de-risk to 1x S&P.\n    if (r !== undefined && r >= 70) return { [ASSET.USLC]: 1 };\n    // Default: hold the 1x index in an uptrend.\n    return { [ASSET.NASDAQ]: 1 };\n  }",
    refs: [
      { name: "trendUp", source: "export function trendUp(ctx: StrategyContext, asset: AssetKey, period = 200): boolean {\n  const p = ctx.level(asset);\n  const ma = ctx.sma(asset, period);\n  return p !== undefined && ma !== undefined && p > ma;\n}" },
      { name: "bestDefensive", source: "export function bestDefensive(ctx: StrategyContext): AssetKey {\n  return bestBy([ASSET.ITT, ASSET.LTT, ASSET.GOLD, ASSET.CASH], (a) => ctx.ret(a, 126), ASSET.CASH);\n}" },
      { name: "rsi", source: "export function rsi(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  let gain = 0;\n  let loss = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    const ch = a - b;\n    if (ch >= 0) gain += ch;\n    else loss -= ch;\n  }\n  const avgLoss = loss / period;\n  if (avgLoss === 0) return 100;\n  const rs = gain / period / avgLoss;\n  return 100 - 100 / (1 + rs);\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "leveragedEquity", source: "export function leveragedEquity(\n  ctx: StrategyContext,\n  oneX: AssetKey,\n  twoX: AssetKey | undefined,\n  threeX: AssetKey | undefined,\n  budget: number,\n  target = 0.3,\n  cap = 2,\n): Weights {\n  const exposure = volTargetExposure(ctx, oneX, target, cap);\n  return scaleWeights(equityExposureWeights(exposure, oneX, twoX, threeX), budget);\n}" },
    ],
  },
  "s8-leverage-long-run": {
    decide: "decide(ctx: StrategyContext): Weights {\n    // Graduated trend strength over an ensemble of MA windows (0..1, ~20% steps).\n    const tf = trendExposure(ctx, ASSET.USLC, [50, 100, 150, 200, 250]);\n    if (tf <= 0) return { [bestDefensive(ctx)]: 1 };\n    // Exposure = trend strength × vol-target, capped at 3x.\n    const E = tf * volTargetExposure(ctx, ASSET.USLC, 0.3, 3);\n    const eq = equityExposureWeights(E, ASSET.USLC, ASSET.USLC2X, ASSET.USLC3X);\n    const invested = Object.values(eq).reduce<number>((s, x) => s + (x ?? 0), 0);\n    // Graduated risk-off: defensive sleeve takes the un-invested remainder.\n    if (invested < 0.999) eq[bestDefensive(ctx)] = Number((1 - invested).toFixed(4));\n    return eq;\n  }",
    refs: [
      { name: "trendExposure", source: "export function trendExposure(\n  ctx: StrategyContext,\n  asset: AssetKey,\n  windows: number[] = [50, 100, 150, 200, 250],\n): number {\n  let up = 0;\n  let n = 0;\n  const p = ctx.level(asset);\n  for (const w of windows) {\n    const ma = ctx.sma(asset, w);\n    if (p !== undefined && ma !== undefined) {\n      n++;\n      if (p > ma) up++;\n    }\n  }\n  return n ? up / n : 0;\n}" },
      { name: "bestDefensive", source: "export function bestDefensive(ctx: StrategyContext): AssetKey {\n  return bestBy([ASSET.ITT, ASSET.LTT, ASSET.GOLD, ASSET.CASH], (a) => ctx.ret(a, 126), ASSET.CASH);\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "volTargetExposure", source: "export function volTargetExposure(\n  ctx: StrategyContext,\n  asset: AssetKey,\n  target: number,\n  cap: number,\n  volDays = 63,\n): number {\n  const v = ctx.vol(asset, volDays) ?? 0.25;\n  return clamp(target / Math.max(v, 0.06), 0, cap);\n}" },
      { name: "equityExposureWeights", source: "export function equityExposureWeights(\n  E: number,\n  oneX: AssetKey,\n  twoX?: AssetKey,\n  threeX?: AssetKey,\n): Weights {\n  const maxE = threeX ? 3 : twoX ? 2 : 1;\n  const e = clamp(E, 0, maxE);\n  if (e <= 1) return e > 0 ? { [oneX]: Number(e.toFixed(4)) } : {};\n  if (e <= 2 && twoX) {\n    const x = e - 1;\n    return { [twoX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  if (threeX) {\n    const x = (e - 1) / 2;\n    return { [threeX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  return { [oneX]: 1 };\n}" },
    ],
  },
  "s9-defensive-asset-allocation": {
    decide: "decide(ctx: StrategyContext): Weights {\n    // Canary breadth: count canary assets with non-positive 13612W momentum.\n    const canary = [ASSET.INTL, ASSET.LTT].filter((a) => ctx.has(a));\n    const bad = canary.filter((a) => (ctx.score13612W(a) ?? -1) <= 0).length;\n    const cashFrac = clamp(bad / (canary.length || 1), 0, 1);\n    const riskyFrac = 1 - cashFrac;\n    // Risky sleeve: stronger of Nasdaq vs S&P by relative momentum, vol-targeted leveraged.\n    const offense = bestBy([ASSET.NASDAQ, ASSET.USLC], (a) => ctx.score13612W(a), ASSET.USLC);\n    const twoX = offense === ASSET.NASDAQ ? ASSET.NASDAQ2X : ASSET.USLC2X;\n    const risky = leveragedEquity(ctx, offense, twoX, undefined, riskyFrac, 0.3, 2);\n    // Defensive sleeve: best-trending bond/gold/cash takes the cash fraction.\n    return capHoldings(addW(risky, { [bestDefensive(ctx)]: cashFrac }), 10);\n  }",
    refs: [
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
      { name: "clamp", source: "export function clamp(x: number, lo: number, hi: number): number {\n  return Math.max(lo, Math.min(hi, x));\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
      { name: "leveragedEquity", source: "export function leveragedEquity(\n  ctx: StrategyContext,\n  oneX: AssetKey,\n  twoX: AssetKey | undefined,\n  threeX: AssetKey | undefined,\n  budget: number,\n  target = 0.3,\n  cap = 2,\n): Weights {\n  const exposure = volTargetExposure(ctx, oneX, target, cap);\n  return scaleWeights(equityExposureWeights(exposure, oneX, twoX, threeX), budget);\n}" },
      { name: "capHoldings", source: "export function capHoldings(w: Weights, maxN: number): Weights {\n  const entries = (Object.entries(w) as [AssetKey, number][]).filter(([, x]) => (x ?? 0) > 0);\n  if (entries.length <= maxN) return w;\n  entries.sort((a, b) => b[1] - a[1]);\n  const kept = entries.slice(0, maxN);\n  const grossAll = entries.reduce((s, [, x]) => s + x, 0);\n  const grossKept = kept.reduce((s, [, x]) => s + x, 0);\n  const scale = grossKept > 0 ? grossAll / grossKept : 1;\n  const out: Weights = {};\n  for (const [a, x] of kept) out[a] = Number((x * scale).toFixed(4));\n  return out;\n}" },
      { name: "addW", source: "export function addW(...weights: Weights[]): Weights {\n  const out: Weights = {};\n  for (const w of weights) {\n    for (const a of Object.keys(w) as AssetKey[]) out[a] = (out[a] ?? 0) + (w[a] ?? 0);\n  }\n  return out;\n}" },
      { name: "bestDefensive", source: "export function bestDefensive(ctx: StrategyContext): AssetKey {\n  return bestBy([ASSET.ITT, ASSET.LTT, ASSET.GOLD, ASSET.CASH], (a) => ctx.ret(a, 126), ASSET.CASH);\n}" },
    ],
  },
};
