/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * The verbatim source of each strategy's decide() (and the helper / indicator
 * functions it calls), surfaced to the UI as the buy/sell signal formula so the
 * displayed math can never drift from the code that runs.
 *
 * Regenerate after editing any decide():
 *   cd backend && node scripts/generate-signal-source.mjs
 *
 * signal-source.spec.ts fails CI if this file is stale.
 */
import type { SignalSource } from '@repo/shared';

export const SIGNAL_SOURCE: Record<string, SignalSource> = {
  "nasdaq-3x-20dma": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const price = ctx.level(ASSET.NASDAQ);\n    const ma = ctx.sma(ASSET.NASDAQ, 20);\n    if (price === undefined || ma === undefined) return {};\n    return price > ma ? { [ASSET.NASDAQ3X]: 1 } : {};\n  }",
    refs: [
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
    ],
  },
  "dual-momentum-gem": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const absMom = ctx.score13612W(ASSET.USLC);\n    if (absMom === undefined || absMom <= 0) {\n      const safe = bestBy([ASSET.CASH, ASSET.ITT, ASSET.LTT], (a) => ctx.score13612W(a), ASSET.ITT);\n      return { [safe]: 1 };\n    }\n    const sUs = absMom;\n    const sIntl = ctx.score13612W(ASSET.INTL);\n    if (sIntl !== undefined && sIntl > sUs) return { [ASSET.INTL]: 1 };\n    return { [ASSET.USLC]: 1 };\n  }",
    refs: [
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
    ],
  },
  "sma-200-trend": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const price = ctx.level(ASSET.USLC);\n    const ma = ctx.sma(ASSET.USLC, 200);\n    if (price === undefined || ma === undefined) {\n      return { [ASSET.ITT]: 1 };\n    }\n    if (price > ma) {\n      const rv = ctx.vol(ASSET.USLC, 20);\n      const e = rv && rv > 0 ? clamp(0.15 / rv, 0.5, 1.5) : 1;\n      return equityExposureWeights(e, ASSET.USLC, ASSET.USLC2X);\n    }\n    const safe = bestBy([ASSET.LTT, ASSET.ITT], (a) => ctx.score13612W(a), ASSET.ITT);\n    return { [safe]: 1 };\n  }",
    refs: [
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "clamp", source: "export function clamp(x: number, lo: number, hi: number): number {\n  return Math.max(lo, Math.min(hi, x));\n}" },
      { name: "equityExposureWeights", source: "export function equityExposureWeights(\n  E: number,\n  oneX: AssetKey,\n  twoX?: AssetKey,\n  threeX?: AssetKey,\n): Weights {\n  const maxE = threeX ? 3 : twoX ? 2 : 1;\n  const e = clamp(E, 0, maxE);\n  if (e <= 1) return e > 0 ? { [oneX]: Number(e.toFixed(4)) } : {};\n  if (e <= 2 && twoX) {\n    const x = e - 1;\n    return { [twoX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  if (threeX) {\n    const x = (e - 1) / 2;\n    return { [threeX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  return { [oneX]: 1 };\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
    ],
  },
  "leverage-long-run": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const price = ctx.level(ASSET.USLC);\n    const ma = ctx.sma(ASSET.USLC, 200);\n    const mom = ctx.ret(ASSET.USLC, DAYS.MONTH);\n    if (price === undefined || ma === undefined || mom === undefined) {\n      return { [ASSET.ITT]: 1 };\n    }\n    if (price > ma && mom > 0) {\n      const rv = ctx.vol(ASSET.USLC, 20);\n      const e = rv && rv > 0 ? clamp(0.3 / rv, 1, 3) : 1;\n      return equityExposureWeights(e, ASSET.USLC, ASSET.USLC2X, ASSET.USLC3X);\n    }\n    const safe = bestBy([ASSET.LTT, ASSET.ITT], (a) => ctx.score13612W(a), ASSET.ITT);\n    return { [safe]: 1 };\n  }",
    refs: [
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
      { name: "ret", source: "export function ret(lv: Levels, i: number, period: number): number | undefined {\n  const now = lv[i];\n  const then = lv[i - period];\n  if (now === undefined || then === undefined) return undefined;\n  return now / then - 1;\n}" },
      { name: "DAYS", source: "export const DAYS = {\n  WEEK: 5,\n  MONTH: 21,\n  QUARTER: 63,\n  HALF_YEAR: 126,\n  YEAR: 252,\n};" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "clamp", source: "export function clamp(x: number, lo: number, hi: number): number {\n  return Math.max(lo, Math.min(hi, x));\n}" },
      { name: "equityExposureWeights", source: "export function equityExposureWeights(\n  E: number,\n  oneX: AssetKey,\n  twoX?: AssetKey,\n  threeX?: AssetKey,\n): Weights {\n  const maxE = threeX ? 3 : twoX ? 2 : 1;\n  const e = clamp(E, 0, maxE);\n  if (e <= 1) return e > 0 ? { [oneX]: Number(e.toFixed(4)) } : {};\n  if (e <= 2 && twoX) {\n    const x = e - 1;\n    return { [twoX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  if (threeX) {\n    const x = (e - 1) / 2;\n    return { [threeX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  return { [oneX]: 1 };\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
    ],
  },
  "accelerating-dual-momentum": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const universe = [ASSET.USLC, ASSET.NASDAQ, ASSET.SMALL, ASSET.INTL];\n    const best = rankBy(universe, (a) => ctx.accel(a))[0];\n    if (best && best.score > 0) return { [best.asset]: 1 };\n    const safe = bestBy([ASSET.CASH, ASSET.ITT, ASSET.LTT], (a) => ctx.score13612W(a), ASSET.LTT);\n    return { [safe]: 1 };\n  }",
    refs: [
      { name: "rankBy", source: "export function rankBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n): { asset: AssetKey; score: number }" },
      { name: "accelMomentum", source: "export function accelMomentum(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined) return undefined;\n  return (r1 + r3 + r6) / 3;\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
    ],
  },
  "sector-momentum": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const price = ctx.level(ASSET.USLC);\n    const ma = ctx.sma(ASSET.USLC, 200);\n    if (price !== undefined && ma !== undefined && price <= ma) {\n      const safe = bestBy([ASSET.LTT, ASSET.ITT], (a) => ctx.score13612W(a), ASSET.ITT);\n      return { [safe]: 1 };\n    }\n    const ranked = rankBy([...SECTOR_ASSETS], (a) => ctx.score13612W(a));\n    const top = ranked.slice(0, 2);\n    const weights: Weights = {};\n    for (const { asset, score } of top) {\n      if (score > 0) weights[asset] = 0.4;\n    }\n    const ittScore = ctx.score13612W(ASSET.ITT);\n    const sleeve = ittScore !== undefined && ittScore > 0 ? ASSET.ITT : ASSET.CASH;\n    if (sleeve === ASSET.ITT) weights[sleeve] = (weights[sleeve] ?? 0) + 0.2;\n    // CASH sleeve is left unallocated (engine treats remainder as cash).\n    return weights;\n  }",
    refs: [
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
      { name: "rankBy", source: "export function rankBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n): { asset: AssetKey; score: number }" },
    ],
  },
  "vol-target-spy": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const price = ctx.level(ASSET.USLC);\n    const ma = ctx.sma(ASSET.USLC, 200);\n    const rv = ctx.vol(ASSET.USLC, 20);\n    const inTrend = price !== undefined && ma !== undefined && price > ma;\n    const targetVol = inTrend ? 0.15 : 0.05;\n    const e = rv && rv > 0 ? clamp(targetVol / rv, 0, 2) : 1;\n    const weights = equityExposureWeights(e, ASSET.USLC, ASSET.USLC2X);\n    if (e < 1) {\n      const rem = 1 - e;\n      const ittScore = ctx.score13612W(ASSET.ITT);\n      if (ittScore !== undefined && ittScore > 0) weights[ASSET.ITT] = Number(rem.toFixed(4));\n      // else: remainder stays in cash (engine default).\n    }\n    return weights;\n  }",
    refs: [
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "clamp", source: "export function clamp(x: number, lo: number, hi: number): number {\n  return Math.max(lo, Math.min(hi, x));\n}" },
      { name: "equityExposureWeights", source: "export function equityExposureWeights(\n  E: number,\n  oneX: AssetKey,\n  twoX?: AssetKey,\n  threeX?: AssetKey,\n): Weights {\n  const maxE = threeX ? 3 : twoX ? 2 : 1;\n  const e = clamp(E, 0, maxE);\n  if (e <= 1) return e > 0 ? { [oneX]: Number(e.toFixed(4)) } : {};\n  if (e <= 2 && twoX) {\n    const x = e - 1;\n    return { [twoX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  if (threeX) {\n    const x = (e - 1) / 2;\n    return { [threeX]: Number(x.toFixed(4)), [oneX]: Number((1 - x).toFixed(4)) };\n  }\n  return { [oneX]: 1 };\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
    ],
  },
  "defensive-asset-allocation": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const offensive: AssetKey[] = [\n      ASSET.USLC,\n      ASSET.NASDAQ,\n      ASSET.SMALL,\n      ASSET.INTL,\n      ASSET.GOLD,\n      ASSET.LTT,\n    ];\n    const defensive: AssetKey[] = [ASSET.CASH, ASSET.ITT, ASSET.LTT];\n    const canaryEquity = ctx.has(ASSET.INTL) ? ASSET.INTL : ASSET.USLC;\n    const cEq = ctx.score13612W(canaryEquity) ?? 0;\n    const cBond = ctx.score13612W(ASSET.ITT) ?? 0;\n    const goodCanaries = (cEq > 0 ? 1 : 0) + (cBond > 0 ? 1 : 0);\n    const bestDef = bestBy(defensive, (a) => ctx.score13612W(a), ASSET.CASH);\n\n    if (goodCanaries === 2) {\n      const w = inverseVolWeights(ctx, offensive, 6, 20, 1);\n      return Object.keys(w).length ? w : { [bestDef]: 1 };\n    }\n    if (goodCanaries === 1) {\n      const w = inverseVolWeights(ctx, offensive, 3, 20, 0.5);\n      w[bestDef] = (w[bestDef] ?? 0) + 0.5;\n      return w;\n    }\n    return { [bestDef]: 1 };\n  }",
    refs: [
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
      { name: "inverseVolWeights", source: "export function inverseVolWeights(\n  ctx: StrategyContext,\n  assets: AssetKey[],\n  k: number,\n  volDays: number,\n  budget = 1,\n): Weights {\n  const ranked = rankBy(assets, (a) => ctx.score13612W(a)).slice(0, k);\n  const raw = ranked.map(({ asset }) => {\n    const v = ctx.vol(asset, volDays);\n    return { asset, inv: v && v > 0 ? 1 / v : 0 };\n  });\n  const total = raw.reduce((s, r) => s + r.inv, 0);\n  const weights: Weights = {};\n  if (total === 0) {\n    // Fall back to equal weight if vol unavailable.\n    for (const { asset } of ranked) weights[asset] = budget / Math.max(1, ranked.length);\n    return weights;\n  }\n  for (const r of raw) if (r.inv > 0) weights[r.asset] = (r.inv / total) * budget;\n  return weights;\n}" },
    ],
  },
  "rsi2-mean-reversion": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const price = ctx.level(ASSET.USLC);\n    const ma200 = ctx.sma(ASSET.USLC, 200);\n    const r = ctx.rsi(ASSET.USLC, 2);\n    const trend = price !== undefined && ma200 !== undefined && price > ma200;\n    let wE = 0;\n    if (trend && r !== undefined && r < 15) {\n      wE = r < 5 ? 1 : r < 10 ? 0.75 : 0.5;\n    }\n    const weights: Weights = {};\n    if (wE > 0) weights[ASSET.USLC] = wE;\n    const rem = 1 - wE;\n    if (rem > 0.001) {\n      const ittScore = ctx.score13612W(ASSET.ITT);\n      if (trend && ittScore !== undefined && ittScore > 0) {\n        weights[ASSET.ITT] = Number(rem.toFixed(2));\n      }\n      // else: remainder stays in cash (engine default).\n    }\n    return weights;\n  }",
    refs: [
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
      { name: "rsi", source: "export function rsi(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  let gain = 0;\n  let loss = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    const ch = a - b;\n    if (ch >= 0) gain += ch;\n    else loss -= ch;\n  }\n  const avgLoss = loss / period;\n  if (avgLoss === 0) return 100;\n  const rs = gain / period / avgLoss;\n  return 100 - 100 / (1 + rs);\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
    ],
  },
  "all-weather": {
    decide: "decide(ctx: StrategyContext): Weights {\n    const sleeves: AssetKey[] = [ASSET.USLC, ASSET.LTT, ASSET.ITT, ASSET.GOLD].filter((a) =>\n      ctx.has(a),\n    );\n    const raw = sleeves.map((a) => {\n      const v = ctx.vol(a, DAYS.QUARTER);\n      return { a, inv: v && v > 0 ? 1 / v : 0 };\n    });\n    const total = raw.reduce((s, r) => s + r.inv, 0);\n    const w: Weights = {};\n    if (total === 0) {\n      for (const a of sleeves) w[a] = 1 / sleeves.length;\n    } else {\n      for (const r of raw) if (r.inv > 0) w[r.a] = r.inv / total;\n    }\n    // Equity trend overlay.\n    const price = ctx.level(ASSET.USLC);\n    const ma = ctx.sma(ASSET.USLC, 200);\n    if (price !== undefined && ma !== undefined && price <= ma && w[ASSET.USLC]) {\n      const safe = bestBy([ASSET.LTT, ASSET.ITT], (a) => ctx.score13612W(a), ASSET.ITT);\n      w[safe] = (w[safe] ?? 0) + w[ASSET.USLC]!;\n      w[ASSET.USLC] = 0;\n    }\n    return w;\n  }",
    refs: [
      { name: "vol", source: "export function vol(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period < 0) return undefined;\n  const rets: number[] = [];\n  for (let k = i - period + 1; k <= i; k++) {\n    const a = lv[k];\n    const b = lv[k - 1];\n    if (a === undefined || b === undefined) return undefined;\n    rets.push(Math.log(a / b));\n  }\n  const mean = rets.reduce((s, x) => s + x, 0) / rets.length;\n  const variance = rets.reduce((s, x) => s + (x - mean) ** 2, 0) / (rets.length - 1);\n  return Math.sqrt(variance) * Math.sqrt(DAYS.YEAR);\n}" },
      { name: "DAYS", source: "export const DAYS = {\n  WEEK: 5,\n  MONTH: 21,\n  QUARTER: 63,\n  HALF_YEAR: 126,\n  YEAR: 252,\n};" },
      { name: "level", source: "export function level(lv: Levels, i: number, lag = 0): number | undefined {\n  const idx = i - lag;\n  return idx >= 0 ? lv[idx] : undefined;\n}" },
      { name: "sma", source: "export function sma(lv: Levels, i: number, period: number): number | undefined {\n  if (i - period + 1 < 0) return undefined;\n  let sum = 0;\n  for (let k = i - period + 1; k <= i; k++) {\n    const v = lv[k];\n    if (v === undefined) return undefined;\n    sum += v;\n  }\n  return sum / period;\n}" },
      { name: "bestBy", source: "export function bestBy(\n  assets: AssetKey[],\n  score: (a: AssetKey) => number | undefined,\n  fallback: AssetKey,\n): AssetKey {\n  return rankBy(assets, score)[0]?.asset ?? fallback;\n}" },
      { name: "score13612W", source: "export function score13612W(lv: Levels, i: number): number | undefined {\n  const r1 = ret(lv, i, DAYS.MONTH);\n  const r3 = ret(lv, i, DAYS.QUARTER);\n  const r6 = ret(lv, i, DAYS.HALF_YEAR);\n  const r12 = ret(lv, i, DAYS.YEAR);\n  if (r1 === undefined || r3 === undefined || r6 === undefined || r12 === undefined)\n    return undefined;\n  return 12 * r1 + 4 * r3 + 2 * r6 + r12;\n}" },
    ],
  },
};
